#Esse profile apenas será executado quando o parâmetro profiles.active for setado como prod,
#assim, no momento da executação do Spring boot é preciso passar o seguinte parâmetro -Dspring.profiles.active=prod,
#sendo exeutado com o comando: mvn spring-boot:run -Dspring.profiles.active=prod.

server:
  port: 8080
  servlet:
    context-path: /api

application:
  description: AquaLogic API
  version: 0.0.0

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/aqualogicdb
    username: postgres
    password: aloisk

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none