
server:
  port: 8080
  servlet:
    context-path: /api

application:
  description: AquaLogic API
  version: 0.0.0

#springDEV:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/aqualogicdb
#    username: postgres
#    password: aloisk
#
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://ucwtgezycizhlm:baec64bcf1c1b4620b7c9f18cdc4369d553697306f37171fc6a0dcba1e42bfca@ec2-44-205-41-76.compute-1.amazonaws.com:5432/daj9as8i9o34g8
    username: ucwtgezycizhlm
    password: baec64bcf1c1b4620b7c9f18cdc4369d553697306f37171fc6a0dcba1e42bfca

    jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: false
      hibernate:
        ddl-auto: none